### ISSUE TITLE
求视频链接地址和学习顺序

### ISSUE THREAD

**Issue by mrbcy** [chuyueZhang/frontEndLearning#1]
大佬，能把视频链接地址和学习顺序贴一下吗？谢谢！

**Comment by chuyueZhang** [comment]
我在readme里添加了视频链接，可以去看看，有什么问题再提~

**Comment by mrbcy** [comment]
非常感谢！不过链接似乎有点问题，从README里面点击的时候会提示404，但是把地址拷贝到地址栏就可以访问

![image](https://user-images.githubusercontent.com/25566489/61356187-64c33e80-a8a8-11e9-9948-aaedf3e79520.png)

**Comment by chuyueZhang** [comment]
刚才研究了下，是B站对跨域请求做了拦截处理，我在readme里加个备注吧~

**Comment by mrbcy** [comment]
👍 B站是学习的好地方哈哈哈
